package demo.finance.cryptoCoin.service;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import test.aiArt.CommonService;

public class BinanceDataCommonService extends CommonService {
	
	protected static final int SCALE_FOR_PRICE_DISPLAY = 8;
	protected static final int SCALE_FOR_PRICE_CALCULATE = 12;
	protected static final int SCALE_FOR_RATE_DISPLAY = 2;
	protected static final int SCALE_FOR_RATE_CALCULATE = 4;

	private static final String FILE_SAVE_PATH = "/tmp/cryptoCoin";
	
	protected static List<String> symbols = new ArrayList<>();
	protected static List<String> kSymbols = new ArrayList<>();
	
	static {
		symbols.addAll(Arrays.asList(
				"SUSHIUSDT,INJUSDT,BNTUSDT,SAGAUSDT,RDNTUSDT,ZRXUSDT,HIGHUSDT,XAIUSDT,SPELLUSDT,BNBUSDT,XTZUSDT,DARUSDT,MEWUSDT,JOEUSDT,ETCUSDT,PENDLEUSDT,XMRUSDT,ALICEUSDT,HOOKUSDT,REZUSDT,ACEUSDT,BNBUSDC,REEFUSDT,BATUSDT,1000BONKUSDT,DOGEUSDT,TRXUSDT,STORJUSDT,SNXUSDT,DOGEUSDC,1000BONKUSDC,XLMUSDT,MATICUSDC,IOTXUSDT,ARKUSDT,OMNIUSDT,UMAUSDT,DASHUSDT,KAVAUSDT,OXTUSDT,APEUSDT,RUNEUSDT,BNXUSDT,LTCUSDC,OPUSDT,KEYUSDT,SKLUSDT,GLMUSDT,ALTUSDT,MTLUSDT,LTCUSDT,RENDERUSDT,GUSDT,ETHBTC,KSMUSDT,FLOWUSDT,TRBUSDT,MANAUSDT,CHRUSDT,WUSDT,ONDOUSDT,AEVOUSDT,OGNUSDT,ENAUSDT,STMXUSDT,BLURUSDT,KNCUSDT,ENJUSDT,XRPUSDC,ATOMUSDT,NMRUSDT,GASUSDT,ENSUSDT,ATAUSDT,IOSTUSDT,HBARUSDT,ZECUSDT,SYNUSDT,POLYXUSDT,BANANAUSDT,EDUUSDT,GALAUSDT,VIDTUSDT,GTCUSDT,ALGOUSDT,MANTAUSDT,LISTAUSDT,BSVUSDT,ALPACAUSDT,LRCUSDT,PYTHUSDT,ENAUSDC,ORBSUSDT,STGUSDT,STXUSDT,ARPAUSDT,CELOUSDT,QNTUSDT,AIUSDT,1INCHUSDT,TUSDT,IOUSDT,PIXELUSDT,TAOUSDT,SOLUSDC,LINAUSDT,ARUSDT,STRKUSDT,FILUSDT,ZETAUSDT,DODOXUSDT,SOLUSDT,AXLUSDT,LOOMUSDT,RONINUSDT,1000SATSUSDT,BLZUSDT,COMBOUSDT,FILUSDC,GMTUSDT,XVSUSDT,GMXUSDT,LDOUSDT,BANDUSDT,XRPUSDT,SYSUSDT,PORTALUSDT,CRVUSDT,BELUSDT,VOXELUSDT,BONDUSDT,DOTUSDT,ONEUSDT,MAVIAUSDT,APTUSDT,SEIUSDT,CRVUSDC,ANKRUSDT,MAVUSDT,MEMEUSDT,API3USDT,ASTRUSDT,HOTUSDT,QTUMUSDT,IOTAUSDT,ETHUSDC,ADAUSDT,JTOUSDT,LSKUSDT,LITUSDT,ZROUSDT,BIGTIMEUSDT,STEEMUSDT,ETHFIUSDT,YFIUSDT,USTCUSDT,ETHUSDT,MYROUSDT,RAREUSDT,ORDIUSDT,ALPHAUSDT,WOOUSDT,SFPUSDT,ETHFIUSDC,RLCUSDT,ORDIUSDC,1000XECUSDT,CFXUSDT,FXSUSDT,BADGERUSDT,IDUSDT,HFTUSDT,UNFIUSDT,NEOUSDT,POWRUSDT,SANDUSDT,WAXPUSDT,MINAUSDT,LINKUSDT,NULSUSDT,RIFUSDT,CELRUSDT,AGLDUSDT,RSRUSDT,RENUSDT,LPTUSDT,JASMYUSDT,NOTUSDT,PHBUSDT,ARBUSDC,YGGUSDT,EGLDUSDT,DYMUSDT,LUNA2USDT,VETUSDT,ONTUSDT,NFPUSDT,IMXUSDT,LQTYUSDT,NEOUSDC,POPCATUSDT,COTIUSDT,ARBUSDT,VANRYUSDT,LINKUSDC,BAKEUSDT,GRTUSDT,AUCTIONUSDT,FLMUSDT,MASKUSDT,EOSUSDT,ZKUSDT,WIFUSDC,NEARUSDC,BALUSDT,BBUSDT,SUIUSDT,METISUSDT,BCHUSDC,DENTUSDT,TRUUSDT,CKBUSDT,SSVUSDT,CYBERUSDT,TOKENUSDT,BRETTUSDT,C98USDT,ZENUSDT,NEARUSDT,TWTUSDT,BEAMXUSDT,SUIUSDC,BCHUSDT,BOMEUSDT,1000SHIBUSDT,TLMUSDT,AVAXUSDC,ETHWUSDT,HIFIUSDT,AAVEUSDT,BICOUSDT,TONUSDT,ICPUSDT,WIFUSDT,1000SHIBUSDC,BOMEUSDC,1000LUNCUSDT,TURBOUSDT,CAKEUSDT,AVAXUSDT,NTRNUSDT,JUPUSDT,MAGICUSDT,ROSEUSDT,MOVRUSDT,OMUSDT,MATICUSDT,ONGUSDT,XVGUSDT,TIAUSDT,MKRUSDT,PEOPLEUSDT,BTCUSDC,THETAUSDT,1000PEPEUSDC,UNIUSDT,PERPUSDT,RVNUSDT,ARKMUSDT,NKNUSDT,KLAYUSDT,DEFIUSDT,TIAUSDC,TNSRUSDT,COMPUSDT,BTCDOMUSDT,BTCUSDT,OMGUSDT,ICXUSDT,1000PEPEUSDT,SUPERUSDT,FETUSDT,1000RATSUSDT,LEVERUSDT,1000FLOKIUSDT,FTMUSDT,AMBUSDT,SXPUSDT,XEMUSDT,WLDUSDT,ZILUSDT,DYDXUSDT,AXSUSDT,WLDUSDC,CHZUSDT,ILVUSDT,DUSKUSDT,CTSIUSDT,KASUSDT,ACHUSDT,SUNUSDT"
//				"MEW,XMR,BNB,REEF,BONK,DOGE,BONK,MATIC,LTC,ONDO,XRP,BSV,ENA,ORBS,SOL,ZETA,DODOX,LOOM,FIL,BOND,MAVIA,CRV,ETH,BIGTIME,MYRO,ETHFI,ORDI,XEC,ARB,LUNA2,NEO,POPCAT,LINK,WIF,NEAR,BCH,TOKEN,BRETT,SUI,SHIB,AVAX,ETHW,SHIB,BOME,LUNC,TURBO,BTC,PEPE,DEFI,TIA,BTCDOM,OMG,PEPE,RATS,FLOKI,XEM,WLD,KAS"
						.split(",")));
		for (String symbol : symbols) {
			if (symbol.startsWith("1000")) {
				kSymbols.add(symbol);
			}
		}
	}

	protected static String getFileSavePath() {
		File z2 = new File("D:/z2");
		if (z2.exists()) {
			return "D:" + FILE_SAVE_PATH;
		} else {
			return System.getProperty("user.home") + FILE_SAVE_PATH;
		}
	}
	
	public static void setProxy() {
		String proxyHost = "127.0.0.1";
		String proxyPort = "10809";
		System.setProperty("http.proxyHost", proxyHost);
		System.setProperty("http.proxyPort", proxyPort);
		System.setProperty("https.proxyHost", proxyHost);
		System.setProperty("https.proxyPort", proxyPort);
	}

}
