package demo.finance.cryptoCoin.service;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class SymbolCheckOldAndNew {

	public static void main(String[] args) {
		String oldStr = "BTC, ETH, BNB, SOL, USDC, XRP, DOGE, ADA, AVAX, SHIB, TRX, WBTC, LINK, DOT, BCH, UNI, NEAR, MATIC, LTC, DAI, PEPE, ICP, ETC, WBETH, APT, RNDR, HBAR, XLM, ATOM, ARB, FIL, STX, IMX, FDUSD, MKR, SUI, VET, GRT, TAO, OP, LDO, INJ, WIF, AR, FLOKI, FTM, THETA, NOT, RUNE, BONK, JASMY, FET, AAVE, TIA, PYTH, ALGO, SEI, JUP, FLOW, STRK, QNT, ENA, PENDLE, GALA, BEAMX, AXS, EOS, BTTC, ORDI, GNO, ZRO, ENS, AGIX, NEO, EGLD, XTZ, RONIN, SAND, WLD, ZK, CHZ, NEXO, SNX, MINA, MANA, DEXE, ROSE, XEC, W, CFX, BOME, LPT, CAKE, KLAY, IOTA, OM, APE, 1INCH, RPL, KAVA, LUNC, CKB, FTT, TUSD, TFUEL, CRV, PAXG, TWT, BLUR, AXL, IOTX, WOO, COMP, PEOPLE, RAY, SSV, ASTR, ETHFI, MEME, AEVO, BNX, OSMO, GLM, IO, ARKM, OCEAN, KSM, 1000SATS, GMT, DYDX, SUPER, SFP, LUNA, MANTA, ZEC, ZIL, HOT, CELO, CVX, ANKR, ILV, ZRX, POLYX, SKL, JTO, ELF, METIS, RSR, DYM, BICO, BAT, RVN, ENJ, DASH, FXS, JST, QTUM, GMX, GAL, SC, DCR, MASK, TRB, ID, GAS, LRC, YGG, FLUX, T, PIXEL, ALT, ONE, UMA, SUSHI, CHR, VANRY, AMP, API3, YFI, ONT, VTHO, LISTA, GLMR, ACH, AUDIO, NTRN, BAL, EDU, BB, TRU, KDA, BAND, MAGIC, RLC, SXP, LSK, ICX, PROM, COTI, STORJ, C98, IOST, WAXP, POND, CTSI, DGB, ONG, XAI, USDP, SLP, CREAM, AI, NMR, SAGA, CELR, DUSK, CYBER, JOE, XNO, ACE, REZ, SUN, IQ, OMNI, BLZ, REQ, CVC, AUCTION, POWR, XVS, USTC, HIVE, SNT, KNC, PORTAL, MOVR, PYR, CTK, SPELL, SYN, PHA, HIGH, ARK, ZEN, PUNDIX, SYS, DENT, RIF, BAKE, GNS, HOOK, PHB, STEEM, WIN, STRAX, MTL, HFT, DODO, NFP, BNT, STG, AGLD, LQTY, SCRT, ALICE, FRONT, MAV, STPT, TNSR, ACA, MBOX, ALPHA, RDNT, LEVER, ARPA, OXT, XVG, QI, DAR, LOOM, GHST, RARE, GTC, BADGER, ARDR, HIFI, NKN, OGN, ORN, AEUR, RAD, TKO, POLS, WRX, LTO, ATA, TLM, QKC, ERN, CLV, COMBO, CTXC, REI, PERP, MBL, DATA, KMD, REN, FORTH, DIA, STMX, MLN, LIT, COS, FUN, NULS, ALCX, FIS, FLM, UNFI, WAN, DEGO, AERGO, BEL, PSG, LINA, MDX, FIDA, VIC, IDEX, LOKA, FARM, AVA, BETA, PDA, REEF, BSW, MDT, QUICK, IRIS, KEY, VOXEL, UTK, BURGER, KP3R, UFT, BIFI, ADX, CHESS, PIVX, WING, BAR, AKRO, FIO, AMB, HARD, VITE, DOCK, VIDT, CITY, ALPACA, GFT, AST, SANTOS, FIRO, VIB, ALPINE, BOND, OG, TROY, VGX, DF, LAZIO, JUV, PORTO, OAX, FOR, PROS, ATM, IDRT, ACM, CVP, EPX, OOKI, ASR";
		String newStr = "BTC, ETH, BNB, SOL, USDC, XRP, DOGE, ADA, TRX, AVAX, SHIB, WBTC, DOT, LINK, BCH, NEAR, DAI, MATIC, LTC, UNI, ICP, PEPE, ETC, XLM, WBETH, APT, FET, MKR, STX, HBAR, FIL, ATOM, RNDR, VET, ARB, IMX, SUI, FDUSD, OP, INJ, GRT, TAO, WIF, AR, NOT, BONK, AAVE, LDO, THETA, FLOKI, FTM, RUNE, TIA, ALGO, JASMY, PYTH, JUP, SEI, EGLD, OM, FLOW, QNT, STRK, AXS, EOS, ENS, BTTC, XTZ, BEAMX, NEO, SAND, RONIN, GALA, ORDI, GNO, ENA, NEXO, MANA, CFX, CHZ, XEC, PENDLE, MINA, ZK, DEXE, KLAY, SNX, ROSE, BOME, IOTA, ASTR, 1INCH, CAKE, AXL, CKB, WLD, TUSD, W, RAY, TFUEL, APE, FTT, LPT, BNX, PAXG, ZEC, KAVA, TWT, 1000SATS, ZRO, LUNC, COMP, AEVO, WOO, IOTX, SFP, PEOPLE, CRV, GMT, KSM, SSV, RPL, DYDX, OSMO, MEME, GLM, LUNA, DASH, ZIL, HOT, JST, CELO, BLUR, ILV, ARKM, MANTA, ANKR, GAL, ENJ, SUPER, ELF, BAT, SC, ZRX, ID, JTO, RVN, DYM, GMX, QTUM, ETHFI, SKL, RSR, GAS, BICO, METIS, IO, MASK, DCR, POLYX, FLUX, CVX, BB, T, EDU, LRC, VTHO, CHR, TRB, YFI, ONE, FXS, ACH, GLMR, AMP, SUSHI, ZEN, UMA, ONT, YGG, VANRY, API3, KDA, AUDIO, BAND, TRU, BAL, STORJ, ICX, SXP, PIXEL, POND, ALT, LSK, NTRN, COTI, RLC, SAGA, WAXP, MAGIC, C98, DGB, IOST, LISTA, ONG, CTSI, PROM, USDP, DUSK, SUN, XNO, JOE, SLP, HIVE, AI, IQ, REQ, CELR, SNT, CVC, OMNI, POWR, GNS, NMR, HIGH, CYBER, XVS, KNC, PHA, PUNDIX, ACE, AUCTION, SPELL, USTC, STRAX, PYR, DENT, PORTAL, XAI, CTK, SYS, MOVR, WIN, STPT, STEEM, SYN, CREAM, RIF, BAKE, HOOK, HFT, PHB, BLZ, LEVER, LQTY, REZ, STG, BNT, DODO, SCRT, DAR, FRONT, MTL, QI, OXT, XVG, ARDR, NFP, ALICE, AGLD, MBOX, LOOM, ACA, RARE, AEUR, ALPHA, RAD, ARPA, HIFI, ARK, NKN, BADGER, RDNT, WRX, TNSR, MLN, GHST, GTC, OGN, TKO, MAV, MDX, ORN, STMX, QKC, LTO, CLV, BETA, REI, FORTH, TLM, ATA, ERN, REN, MBL, KMD, PERP, DIA, PDA, AERGO, FIS, COS, FLM, LIT, FUN, DATA, POLS, ALCX, WAN, CTXC, COMBO, NULS, AVA, DEGO, LINA, BEL, IDEX, PSG, UNFI, FIDA, VIC, MDT, BSW, REEF, FARM, LOKA, QUICK, UTK, KEY, VOXEL, BIFI, ADX, KP3R, UFT, AKRO, WING, IRIS, BURGER, BAR, PIVX, CHESS, FIO, ALPACA, AMB, CITY, GFT, VIDT, FIRO, VITE, VGX, AST, ALPINE, HARD, OG, BOND, TROY, SANTOS, VIB, ASR, OOKI, DF, JUV, LAZIO, PORTO, OAX, PROS, IDRT, FOR, ATM, ACM, EPX, DOCK, CVP";

		List<String> oldList = new ArrayList<>();
		oldList.addAll(Arrays.asList(oldStr.replaceAll(" ", "").split(",")));
		List<String> newList = new ArrayList<>();
		newList.addAll(Arrays.asList(newStr.replaceAll(" ", "").split(",")));
		System.out.println("old size: " + oldList.size());
		System.out.println("new size: " + newList.size());

		List<String> deleted = new ArrayList<>();
		for (int i = 0; i < oldList.size(); i++) {
			String old = oldList.get(i);
			if (!newList.contains(old)) {
				deleted.add(old);
			}
		}

		List<String> added = new ArrayList<>();
		for (int i = 0; i < newList.size(); i++) {
			String n = newList.get(i);
			if (!oldList.contains(n)) {
				added.add(n);
			}
		}

		System.out.println("deleted: " + deleted);
		System.out.println("new : " + added);
	}
}
