package test;

import java.io.IOException;
import java.net.URISyntaxException;

import net.sf.json.JSONObject;
import test.pojo.type.BrownDust2ItemType;
import toolPack.httpHandel.HttpUtil;

public class BrownDust2 {

	private static String url = "http://127.0.0.1:5000/Account/SendMail";
	private static HttpUtil h = new HttpUtil();
	private static JSONObject json = new JSONObject();
	static {
		json.put("uid", "Guest_10004");
		json.put("count", 9999);
	}

	public static void main(String[] args) throws IOException {
//		sendMainResource(1);
//		sendTuYang1(1);
		sendCaiLiao(1);
//		sendRice(1);
//		sendRedSlime(1);
	}

	public static void sendMainResource(int count) {
		json.put("count", 99999999);
		updateJson(BrownDust2ItemType.diamond);
		send(count);

		updateJson(BrownDust2ItemType.money);
		send(count);
		json.put("count", 9999);
	}

	public static void sendCaiLiao(int count) {
		updateJson(BrownDust2ItemType.caiLiao1);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao2);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao3);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao4);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao5);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao6);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao7);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao8);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao9);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao10);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao11);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao12);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao13);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao14);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao15);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao16);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao17);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao18);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao19);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao20);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao21);
		send(count);
		updateJson(BrownDust2ItemType.caiLiao22);
		send(count);
		updateJson(BrownDust2ItemType.jingLianShi);
		send(count);
		updateJson(BrownDust2ItemType.jingLianShuiJing);
		send(count);
		updateJson(BrownDust2ItemType.yuanGuShuiJing);
		send(count);
		updateJson(BrownDust2ItemType.keYinZhouShu);
		send(count);
		updateJson(BrownDust2ItemType.jingSui1);
		send(count);
		updateJson(BrownDust2ItemType.jingSui2);
		send(count);
		updateJson(BrownDust2ItemType.jingSui3);
		send(count);
		updateJson(BrownDust2ItemType.jueXingLingYao);
		send(count);

		updateJson(BrownDust2ItemType.moShi1);
		send(count);
		updateJson(BrownDust2ItemType.moShi2);
		send(count);
		updateJson(BrownDust2ItemType.moShi3);
		send(count);
		updateJson(BrownDust2ItemType.moShi4);
		send(count);
		updateJson(BrownDust2ItemType.moShi5);
		send(count);
		updateJson(BrownDust2ItemType.moShi6);
		send(count);
		updateJson(BrownDust2ItemType.moShi7);
		send(count);
		updateJson(BrownDust2ItemType.moShi8);
		send(count);
		updateJson(BrownDust2ItemType.moShi9);
		send(count);
		updateJson(BrownDust2ItemType.moShi10);
		send(count);
		updateJson(BrownDust2ItemType.moShi11);
		send(count);
		updateJson(BrownDust2ItemType.moShi12);
		send(count);
		updateJson(BrownDust2ItemType.moShi13);
		send(count);
		updateJson(BrownDust2ItemType.moShi14);
		send(count);
		updateJson(BrownDust2ItemType.moShi15);
		send(count);
		updateJson(BrownDust2ItemType.moShi16);
		send(count);
		updateJson(BrownDust2ItemType.moShi17);
		send(count);
		updateJson(BrownDust2ItemType.moShi18);
		send(count);

		updateJson(BrownDust2ItemType.nvShenZhiLei);
		send(count);

		updateJson(BrownDust2ItemType.wuPin1);
		send(count);
		updateJson(BrownDust2ItemType.wuPin2);
		send(count);
		updateJson(BrownDust2ItemType.wuPin3);
		send(count);
		updateJson(BrownDust2ItemType.wuPin4);
		send(count);
		updateJson(BrownDust2ItemType.wuPin5);
		send(count);
		updateJson(BrownDust2ItemType.wuPin6);
		send(count);
		updateJson(BrownDust2ItemType.wuPin7);
		send(count);
		updateJson(BrownDust2ItemType.wuPin8);
		send(count);
		updateJson(BrownDust2ItemType.wuPin9);
		send(count);
		updateJson(BrownDust2ItemType.wuPin10);
		send(count);
		updateJson(BrownDust2ItemType.wuPin11);
		send(count);
		updateJson(BrownDust2ItemType.wuPin12);
		send(count);
		updateJson(BrownDust2ItemType.wuPin13);
		send(count);
		updateJson(BrownDust2ItemType.wuPin14);
		send(count);
		updateJson(BrownDust2ItemType.wuPin15);
		send(count);
		updateJson(BrownDust2ItemType.wuPin16);
		send(count);
		updateJson(BrownDust2ItemType.wuPin17);
		send(count);
		updateJson(BrownDust2ItemType.wuPin18);
		send(count);
		updateJson(BrownDust2ItemType.wuPin19);
		send(count);
		updateJson(BrownDust2ItemType.wuPin20);
		send(count);
		updateJson(BrownDust2ItemType.wuPin21);
		send(count);
		updateJson(BrownDust2ItemType.wuPin22);
		send(count);
		updateJson(BrownDust2ItemType.wuPin23);
		send(count);
		updateJson(BrownDust2ItemType.wuPin24);
		send(count);
		updateJson(BrownDust2ItemType.wuPin25);
		send(count);
		updateJson(BrownDust2ItemType.wuPin26);
		send(count);
		updateJson(BrownDust2ItemType.wuPin27);
		send(count);
		updateJson(BrownDust2ItemType.wuPin28);
		send(count);
		updateJson(BrownDust2ItemType.wuPin29);
		send(count);
		updateJson(BrownDust2ItemType.wuPin30);
		send(count);
		updateJson(BrownDust2ItemType.wuPin31);
		send(count);
		updateJson(BrownDust2ItemType.wuPin32);
		send(count);

		updateJson(BrownDust2ItemType.upgradeStart1);
		send(count);
		updateJson(BrownDust2ItemType.upgradeStart2);
		send(count);
		updateJson(BrownDust2ItemType.upgradeStart3);
		send(count);
		updateJson(BrownDust2ItemType.upgradeStart4);
		send(count);
		updateJson(BrownDust2ItemType.upgradeStart5);
		send(count);
	}

	public static void sendRice(int count) {
		updateJson(BrownDust2ItemType.rice);
		send(count);
	}

	public static void sendRedSlime(int count) {
		updateJson(BrownDust2ItemType.redSlime);
		send(count);
	}

	public static void sendTuYang1(int count) {
		updateJson(BrownDust2ItemType.tuYang1);
		send(count);
		updateJson(BrownDust2ItemType.tuYang2);
		send(count);
		updateJson(BrownDust2ItemType.tuYang3);
		send(count);
		updateJson(BrownDust2ItemType.tuYang4);
		send(count);
		updateJson(BrownDust2ItemType.tuYang5);
		send(count);
		updateJson(BrownDust2ItemType.tuYang6);
		send(count);
		updateJson(BrownDust2ItemType.tuYang7);
		send(count);
		updateJson(BrownDust2ItemType.tuYang8);
		send(count);
		updateJson(BrownDust2ItemType.tuYang9);
		send(count);
		updateJson(BrownDust2ItemType.tuYang10);
		send(count);
		updateJson(BrownDust2ItemType.tuYang11);
		send(count);
		updateJson(BrownDust2ItemType.tuYang12);
		send(count);
		updateJson(BrownDust2ItemType.tuYang13);
		send(count);
		updateJson(BrownDust2ItemType.tuYang14);
		send(count);
		updateJson(BrownDust2ItemType.tuYang15);
		send(count);
		updateJson(BrownDust2ItemType.tuYang16);
		send(count);
		updateJson(BrownDust2ItemType.tuYang17);
		send(count);
		updateJson(BrownDust2ItemType.tuYang18);
		send(count);
		updateJson(BrownDust2ItemType.tuYang19);
		send(count);
		updateJson(BrownDust2ItemType.tuYang20);
		send(count);
		updateJson(BrownDust2ItemType.tuYang21);
		send(count);
		updateJson(BrownDust2ItemType.tuYang22);
		send(count);
		updateJson(BrownDust2ItemType.tuYang23);
		send(count);
		updateJson(BrownDust2ItemType.tuYang24);
		send(count);
		updateJson(BrownDust2ItemType.tuYang25);
		send(count);
		updateJson(BrownDust2ItemType.tuYang26);
		send(count);
		updateJson(BrownDust2ItemType.tuYang27);
		send(count);
		updateJson(BrownDust2ItemType.tuYang28);
		send(count);
		updateJson(BrownDust2ItemType.tuYang29);
		send(count);
		updateJson(BrownDust2ItemType.tuYang30);
		send(count);
		updateJson(BrownDust2ItemType.tuYang31);
		send(count);
		updateJson(BrownDust2ItemType.tuYang32);
		send(count);
		updateJson(BrownDust2ItemType.tuYang33);
		send(count);
		updateJson(BrownDust2ItemType.tuYang34);
		send(count);
		updateJson(BrownDust2ItemType.tuYang35);
		send(count);
		updateJson(BrownDust2ItemType.tuYang36);
		send(count);
		updateJson(BrownDust2ItemType.tuYang37);
		send(count);
		updateJson(BrownDust2ItemType.tuYang38);
		send(count);
		updateJson(BrownDust2ItemType.tuYang39);
		send(count);
		updateJson(BrownDust2ItemType.tuYang40);
		send(count);
		updateJson(BrownDust2ItemType.tuYang41);
		send(count);
		updateJson(BrownDust2ItemType.tuYang42);
		send(count);
		updateJson(BrownDust2ItemType.tuYang43);
		send(count);
		updateJson(BrownDust2ItemType.tuYang44);
		send(count);
		updateJson(BrownDust2ItemType.tuYang45);
		send(count);
		updateJson(BrownDust2ItemType.tuYang46);
		send(count);
		updateJson(BrownDust2ItemType.tuYang47);
		send(count);
		updateJson(BrownDust2ItemType.tuYang48);
		send(count);
		updateJson(BrownDust2ItemType.tuYang49);
		send(count);
		updateJson(BrownDust2ItemType.tuYang50);
		send(count);
		updateJson(BrownDust2ItemType.tuYang51);
		send(count);
		updateJson(BrownDust2ItemType.tuYang52);
		send(count);
		updateJson(BrownDust2ItemType.tuYang53);
		send(count);
		updateJson(BrownDust2ItemType.tuYang54);
		send(count);
		updateJson(BrownDust2ItemType.tuYang55);
		send(count);
		updateJson(BrownDust2ItemType.tuYang56);
		send(count);
		updateJson(BrownDust2ItemType.tuYang57);
		send(count);
		updateJson(BrownDust2ItemType.tuYang58);
		send(count);
		updateJson(BrownDust2ItemType.tuYang59);
		send(count);
		updateJson(BrownDust2ItemType.tuYang60);
		send(count);
		updateJson(BrownDust2ItemType.tuYang61);
		send(count);
		updateJson(BrownDust2ItemType.tuYang62);
		send(count);
		updateJson(BrownDust2ItemType.tuYang63);
		send(count);
		updateJson(BrownDust2ItemType.tuYang64);
		send(count);
		updateJson(BrownDust2ItemType.tuYang65);
		send(count);
		updateJson(BrownDust2ItemType.tuYang66);
		send(count);
		updateJson(BrownDust2ItemType.tuYang67);
		send(count);
		updateJson(BrownDust2ItemType.tuYang68);
		send(count);
		updateJson(BrownDust2ItemType.tuYang69);
		send(count);
		updateJson(BrownDust2ItemType.tuYang70);
		send(count);
		updateJson(BrownDust2ItemType.tuYang71);
		send(count);
		updateJson(BrownDust2ItemType.tuYang72);
		send(count);
		updateJson(BrownDust2ItemType.tuYang73);
		send(count);
		updateJson(BrownDust2ItemType.tuYang74);
		send(count);
		updateJson(BrownDust2ItemType.tuYang75);
		send(count);
		updateJson(BrownDust2ItemType.tuYang76);
		send(count);
		updateJson(BrownDust2ItemType.tuYang77);
		send(count);
		updateJson(BrownDust2ItemType.tuYang78);
		send(count);
		updateJson(BrownDust2ItemType.tuYang79);
		send(count);
		updateJson(BrownDust2ItemType.tuYang80);
		send(count);
		updateJson(BrownDust2ItemType.tuYang81);
		send(count);
		updateJson(BrownDust2ItemType.tuYang82);
		send(count);
		updateJson(BrownDust2ItemType.tuYang83);
		send(count);
		updateJson(BrownDust2ItemType.tuYang84);
		send(count);
		updateJson(BrownDust2ItemType.tuYang85);
		send(count);
		updateJson(BrownDust2ItemType.tuYang86);
		send(count);
		updateJson(BrownDust2ItemType.tuYang87);
		send(count);
		updateJson(BrownDust2ItemType.tuYang88);
		send(count);
		updateJson(BrownDust2ItemType.tuYang89);
		send(count);
		updateJson(BrownDust2ItemType.tuYang90);
		send(count);
		updateJson(BrownDust2ItemType.tuYang91);
		send(count);
		updateJson(BrownDust2ItemType.tuYang92);
		send(count);
		updateJson(BrownDust2ItemType.tuYang93);
		send(count);
		updateJson(BrownDust2ItemType.tuYang94);
		send(count);
		updateJson(BrownDust2ItemType.tuYang95);
		send(count);
		updateJson(BrownDust2ItemType.tuYang96);
		send(count);
		updateJson(BrownDust2ItemType.tuYang97);
		send(count);
		updateJson(BrownDust2ItemType.tuYang98);
		send(count);
		updateJson(BrownDust2ItemType.tuYang99);
		send(count);
		updateJson(BrownDust2ItemType.tuYang100);
		send(count);
		updateJson(BrownDust2ItemType.tuYang101);
		send(count);
		updateJson(BrownDust2ItemType.tuYang102);
		send(count);
		updateJson(BrownDust2ItemType.tuYang103);
		send(count);
		updateJson(BrownDust2ItemType.tuYang104);
		send(count);
		updateJson(BrownDust2ItemType.tuYang105);
		send(count);
		updateJson(BrownDust2ItemType.tuYang106);
		send(count);
		updateJson(BrownDust2ItemType.tuYang107);
		send(count);
		updateJson(BrownDust2ItemType.tuYang108);
		send(count);
		updateJson(BrownDust2ItemType.tuYang109);
		send(count);
		updateJson(BrownDust2ItemType.tuYang110);
		send(count);
		updateJson(BrownDust2ItemType.tuYang111);
		send(count);
		updateJson(BrownDust2ItemType.tuYang112);
		send(count);
		updateJson(BrownDust2ItemType.tuYang113);
		send(count);
		updateJson(BrownDust2ItemType.tuYang114);
		send(count);
		updateJson(BrownDust2ItemType.tuYang115);
		send(count);
		updateJson(BrownDust2ItemType.tuYang116);
		send(count);
		updateJson(BrownDust2ItemType.tuYang117);
		send(count);
		updateJson(BrownDust2ItemType.tuYang118);
		send(count);
		updateJson(BrownDust2ItemType.tuYang119);
		send(count);
		updateJson(BrownDust2ItemType.tuYang120);
		send(count);
	}

	private static void send(int count) {
		System.out.println(json.toString());
		for (int i = 0; i < count; i++) {
			System.out.println(i);
			try {
				h.sendPostRestful(url, json.toString());
			} catch (IOException e) {
				e.printStackTrace();
			} catch (URISyntaxException e) {
				e.printStackTrace();
			}
		}
	}

	private static void updateJson(BrownDust2ItemType itemType) {
		json.put("itemId", itemType.getItemId());
		json.put("type", itemType.getType());
	}
}
